---
- name: instalar dependencias da aplicação
  hosts: app

  tasks:
  - name: Instalar dependencias
    apt:
     name: ['apt-transport-https','ca-certificates','curl','gnupg-agent','software-properties-common']
     state: latest

  - name: adicionar chave do repositorio do Dockek
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    args:
      warn: no

  - name: adicionar repositorio do Dockek
    apt_repository:
      repo: deb [arch=amd64] http://download.docker.com/linux/ubuntu xenial stable 
      state: present

  - name: adicionar ultima versao do Docker
    apt:
      name: ['docker-ce', 'docker-ce-cli','containerd.io']

  - name: Instalar docker-composer
    shell: curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose ; chmod 775 /usr/local/bin/docker-compose
    args:
      warn: no
   
