---
- name: instalar aplicação
  hosts: app

  tasks:
  - name: Instalar aplicação
    git: 
     repo: 'https://github.com/alexfrt/photoshare.git'
     dest: /home/app/public_html

  - name: requerimento
    apt:
      name: ['python-yaml', 'python3-pip']
      state: latest

  - name: Requerimento para o compose
    pip:
      name: docker-compose

  - name: Subir a aplicação
    docker_compose:
      project_src: /home/app/public_html
      state: absent

  - name: criar e subir servicos
    docker_compose:
      project_src: /home/app/public_html
    register: output

  - debug:
      var: output

  - name: Subir novamente
    docker_compose:
      project_src: /home/app/public_html
      build: no
    register: output

  - debug:
      var: output
