---
- name: instalar MetricBeat
  hosts: elk

  tasks:
  - name: Baixar e instalar
    shell: cd /tmp && curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.2-amd64.deb && dpkg -i metricbeat-7.4.2-amd64.deb
    args:
      warn: no
    register: output

  - debug:
      var: output

  - name: Setup
    shell: metricbeat setup 
    args:
      warn: no
    register: output

  - debug:
      var: output

  - name: Iniciar
    shell: metricbeat -e &
    args:
      warn: no
    register: output
  
  - debug:
      var: output
